export const PARTY_MAX_SIZE = 4;
export const FIXED_STEP_MS = 1000 / 60;
export const CURRENT_STATE_VERSION = 1;

export const REALITY_CLASSES = Object.freeze([
  'FICTIONAL_WORLD',
  'SIMULATION',
  'DIGITAL_TWIN',
  'PHYSICAL_SHADOW',
  'PHYSICAL_CONTROL',
  'MIXED_OR_UNKNOWN'
]);

export const CONTROLLER_CLASSES = Object.freeze([
  'LOCAL_HUMAN',
  'LOCAL_DETERMINISTIC',
  'REMOTE_DETERMINISTIC',
  'REMOTE_OLLAMA'
]);

export const ALLOWED_COMPANION_INTENTS = Object.freeze([
  'FOLLOW_HUMAN',
  'EXPLORE_LEFT',
  'EXPLORE_RIGHT',
  'ATTACK_NEAREST',
  'SIGNAL_HIGH_LOW',
  'RETURN_TO_RESTORATION',
  'REST',
  'HOLD_POSITION'
]);

export const RESOURCE_BANDS = Object.freeze([
  'AVAILABLE_MARGIN',
  'RESTORATION_AWARE',
  'RESTORATION_RECOMMENDED',
  'RETURN_MARGIN_LOW',
  'PROTECTIVE_RETURN_OR_HALT'
]);

export const SYNC_RESULTS = Object.freeze([
  'PARTIAL_SYNC',
  'GOOD_SYNC',
  'EXCELLENT_SYNC',
  'SYNCHRONIZED_CRITICAL',
  'BROKEN_OR_ABORTED'
]);
